#
# System dependent settings 
#
# $Id: make.inc,v 1.1 2006/09/06 12:14:56 valcke Exp $
#
##### User configurable options #####
#
# Note: The absolute path name must be indicated.
#
# Note: Choose one of these includes files and modify it according to your
#       local settings. Replace the currently active file with your own.
#
include  $(HOME)/prism/src/mod/oasis3/util/make_dir/make.pgi_cerfacs
#include $(HOME)/prism/src/mod/oasis3/util/make_dir/make.sx_frontend
#include $(TEMP)/prism/src/mod/oasis3/util/make_dir/make.aix
#
#
### End User configurable options ###
